# Generated by Django 3.2 on 2026-03-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('category_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories_courses', to='l_console.category_course')),
            ],
        ),
        migrations.CreateModel(
            name='lms_con',
            fields=[
                ('model_name', models.CharField(max_length=100)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('course_title', models.CharField(max_length=255)),
                ('course_short_description', models.CharField(max_length=500)),
                ('course_detailed_description', models.TextField()),
                ('course_type', models.CharField(choices=[('Academic', 'Academic'), ('Professional', 'Professional'), ('Certification', 'Certification'), ('Skill', 'Skill')], max_length=30)),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=30)),
                ('course_duration', models.CharField(max_length=50)),
                ('number_of_modules', models.IntegerField(blank=True, null=True)),
                ('number_of_lessons', models.IntegerField(blank=True, null=True)),
                ('module_title', models.CharField(max_length=255)),
                ('lesson_title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('Video', 'Video'), ('PDF', 'PDF'), ('PPT', 'PPT'), ('Audio', 'Audio'), ('SCORM', 'SCORM'), ('Live Session', 'Live Session')], max_length=30)),
                ('content_url_upload', models.FileField(upload_to='courses/content/')),
                ('preview_enabled', models.BooleanField(default=False)),
                ('enrollment_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Restricted', 'Restricted')], max_length=30)),
                ('enrollment_start_date', models.DateField(blank=True, null=True)),
                ('enrollment_end_date', models.DateField(blank=True, null=True)),
                ('access_duration', models.CharField(choices=[('Lifetime', 'Lifetime'), ('Fixed Period', 'Fixed Period')], max_length=30)),
                ('prerequisite_courses', models.CharField(max_length=255)),
                ('user_roles_allowed', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Partner', 'Partner')], max_length=50)),
                ('course_price', models.FloatField(blank=True, null=True)),
                ('discount_type_value', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_applicable', models.BooleanField(default=0)),
                ('certificate_available', models.BooleanField(default=0)),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='courses/certificates/')),
                ('minimum_completion_percentage', models.FloatField(blank=True, null=True)),
                ('category_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='l_console.category_course')),
                ('sub_category_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='l_console.sub_category_course')),
            ],
        ),
    ]
